# Generated by Django 3.2.25 on 2024-10-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEntrepreneure', models.CharField(max_length=100)),
                ('prenomEntrepreneure', models.CharField(max_length=100)),
                ('dateNaissanceEntrepreneure', models.DateField()),
                ('secteurActivite', models.CharField(max_length=100)),
                ('paysActivite', models.CharField(max_length=100)),
                ('regionActivite', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
    ]
