# Generated by Django 3.2.25 on 2024-10-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
    ]
