# Generated by Django 3.2.25 on 2024-10-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('register', '0002_auto_20241001_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneur',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='entrepreneur_groups', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='entrepreneur_permissions', to='auth.Permission'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
